import { Task } from "./interfaces/task";

export const mockTasks: Task[] = [
  {
    "assignee": "94785",
    "actions": [
      {
        "id": "cancel",
        "title": "Cancel task",
      },
      {
        "id": "complete",
        "title": "Mark as done",
      },
      {
        "id": "reassign",
        "title": "Reassign task",
      },
      {
        "id": "unclaim",
        "title": "Unassign task",
      },
    ],
    "assigneeName": null,
    "auto_assigned": false,
    "caseCategory": "protection",
    "caseName": "Bob Smith",
    "case_category": "protection",
    "case_id": "1612969732000512",
    "case_name": "Bob Smith",
    "case_type_id": "Asylum",
    "created_date": "2021-02-10T15:08:57.860+0000",
    "dueDate": "2021-02-12T15:08:57.801+0000",
    "due_date": "2021-02-12T15:08:57.801+0000",
    "execution_type": "Case Management Task",
    "id": "e6174446-6bb1-11eb-9648-36aa6357de32",
    "jurisdiction": "IA",
    "location": "765324",
    "location_name": "Taylor House",
    "name": "task name",
    "region": "1",
    "security_classification": "PUBLIC",
    "taskName": "task name",
    "task_state": "assigned",
    "task_system": "SELF",
    "task_title": "task name",
    "type": "wa-task-configuration-api-task",
  },
  {
    "actions": [
      {
        "id": "assign",
        "title": "Assign task",
      },
      {
        "id": "cancel",
        "title": "Cancel task",
      },
      {
        "id": "complete",
        "title": "Mark as done",
      },
    ],
    "assigneeName": null,
    "auto_assigned": false,
    "caseCategory": "protection",
    "caseName": "Bob Smith",
    "case_category": "protection",
    "case_id": "1612969886074875",
    "case_name": "Bob Smith",
    "case_type_id": "Asylum",
    "created_date": "2021-02-10T15:11:31.296+0000",
    "dueDate": "2021-02-12T15:11:31.228+0000",
    "due_date": "2021-02-12T15:11:31.228+0000",
    "execution_type": "Case Management Task",
    "id": "418bbe7c-6bb2-11eb-90a4-ca812cb2b2a3",
    "jurisdiction": "IA",
    "location": "765324",
    "location_name": "Taylor House",
    "name": "task name",
    "region": "1",
    "security_classification": "PUBLIC",
    "taskName": "task name",
    "task_state": "unassigned",
    "task_system": "SELF",
    "task_title": "task name",
    "type": "wa-task-configuration-api-task",
  },
  {
    "actions": [
      {
        "id": "cancel",
        "title": "Cancel task",
      },
      {
        "id": "complete",
        "title": "Mark as done",
      },
      {
        "id": "reassign",
        "title": "Reassign task",
      },
      {
        "id": "unclaim",
        "title": "Unassign task",
      },
    ],
    "assignee": "77c0e306-0354-4264-b45c-f095e464355b",
    "assigneeName": null,
    "auto_assigned": false,
    "caseCategory": "protection",
    "caseName": "Bob Smith",
    "case_category": "protection",
    "case_id": "1612969989251149",
    "case_name": "Bob Smith",
    "case_type_id": "Asylum",
    "created_date": "2021-02-10T15:13:13.905+0000",
    "dueDate": "2021-02-12T15:13:13.844+0000",
    "due_date": "2021-02-12T15:13:13.844+0000",
    "execution_type": "Case Management Task",
    "id": "7eb4a2e1-6bb2-11eb-90a4-ca812cb2b2a3",
    "jurisdiction": "IA",
    "location": "765324",
    "location_name": "Taylor House",
    "name": "task name",
    "region": "1",
    "security_classification": "PUBLIC",
    "taskName": "task name",
    "task_state": "assigned",
    "task_system": "SELF",
    "task_title": "task name",
    "type": "wa-task-configuration-api-task",
  },
];
