import type { Page } from '@playwright/test';

export function buildCreateCaseLocators(page: Page) {
  const doYouAgreeGroup = page.getByRole('group', { name: /Do you agree\?/i });
  const refreshModal = page.locator('.refresh-modal');

  return {
    container: page.locator('exui-case-home'),
    caseDetailsContainer: page.locator('exui-case-details-home'),
    caseAlertSuccessMessage: page.locator('.hmcts-banner--success .alert-message, .exui-alert .alert-message').first(),
    createCaseButton: page
      .getByRole('link', { name: 'Create case' })
      .or(page.locator('a[href="/cases/case-filter"].hmcts-primary-navigation__link')),
    jurisdictionSelect: page.locator('#cc-jurisdiction'),
    caseTypeSelect: page.locator('#cc-case-type'),
    eventTypeSelect: page.locator('#cc-event'),
    startButton: page.locator('button[type="submit"]'),
    submitButton: page.getByRole('button', { name: /^submit\b/i }),
    continueButton: page.getByRole('button', { name: /^continue\b/i }),

    legalRepParty1Block: page.locator('#LegalRepParty1Flags_LegalRepParty1Flags'),
    legalRepParty2Block: page.locator('#LegalRepParty2Flags_LegalRepParty2Flags'),
    party1RoleOnCase: page.locator('#LegalRepParty1Flags_roleOnCase'),
    party1Name: page.locator('#LegalRepParty1Flags_partyName'),
    party1GroupId: page.locator('#LegalRepParty1Flags_groupId'),
    party1Visibility: page.locator('#LegalRepParty1Flags_visibility'),
    party2RoleOnCase: page.locator('#LegalRepParty2Flags_roleOnCase'),
    party2Name: page.locator('#LegalRepParty2Flags_partyName'),
    party2GroupId: page.locator('#LegalRepParty2Flags_groupId'),
    party2Visibility: page.locator('#LegalRepParty2Flags_visibility'),

    textFieldInput: page.locator('#TextField'),
    emailFieldInput: page.locator('#EmailField'),
    phoneNumberFieldInput: page.locator('#PhoneUKField'),
    dateFieldDayInput: page.locator('#DateField-day'),
    dateFieldMonthInput: page.locator('#DateField-month'),
    dateFieldYearInput: page.locator('#DateField-year'),
    dateTimeFieldDayInput: page.locator('#DateTimeField-day'),
    dateTimeFieldMonthInput: page.locator('#DateTimeField-month'),
    dateTimeFieldYearInput: page.locator('#DateTimeField-year'),
    dateTimeFieldHourInput: page.locator('#DateTimeField-hour'),
    dateTimeFieldMinuteInput: page.locator('#DateTimeField-minute'),
    dateTimeFieldSecondInput: page.locator('#DateTimeField-second'),
    currencyFieldInput: page.locator('#AmountInGBPField'),
    yesNoRadioButtons: page.locator('#YesOrNoField'),
    applicantPostcode: page.locator('#AppicantPostcodeField'),
    complexType1JudgeIsRightRadios: page.locator('#ComplexType_1_judgeLevelRadio'),
    complexType1LevelOfJudgeRadioButtons: page.locator('#ComplexType_1_proposal'),
    complexType1LevelOfJudgeDetailsInput: page.locator('#ComplexType_1_proposalReason'),
    complexType1LevelOfJudgeKeyInput: page.locator('#ComplexType_1_TextField'),
    complexType2AddressLine1Input: page.locator('#ComplexType_2_address__detailAddressLine1'),
    complexType2EmailInput: page.locator('#ComplexType_2_email'),
    complexType3ComplianceButton: page.locator('#ComplexType_3_responses button'),
    complexType3ComplianceInput: page.locator('#ComplexType_3_responses input'),
    complexType3DateOfBirthDay: page.locator('#dateOfBirth-day'),
    complexType3DateOfBirthMonth: page.locator('#dateOfBirth-month'),
    complexType3DateOfBirthYear: page.locator('#dateOfBirth-year'),
    complexType3FileUploadInput: page.locator('#ComplexType_3_document'),
    complexType3DateOfHearingDay: page.locator('#dateTimeUploaded-day'),
    complexType3DateOfHearingMonth: page.locator('#dateTimeUploaded-month'),
    complexType3DateOfHearingYear: page.locator('#dateTimeUploaded-year'),
    complexType3DateOfHearingHour: page.locator('#dateTimeUploaded-hour'),
    complexType3DateOfHearingMinute: page.locator('#dateTimeUploaded-minute'),
    complexType3DateOfHearingSecond: page.locator('#dateTimeUploaded-second'),
    complexType4AmountInput: page.locator('#ComplexType_4_amount'),
    complexType4FirstTickBox: page.locator('#ComplexType_4_selectedCategories-item_1'),
    complexType4SelectList: page.locator('#ComplexType_4_FixedListField'),

    genderRadioButtons: page.locator('#Gender .multiple-choice'),
    person1Title: page.locator('#Person1_Title'),
    person1TitleInput: page.locator('#Person1_Title'),
    person1FirstNameInput: page.locator('#Person1_FirstName'),
    person1MaidenNameInput: page.locator('#Person1_MaidenName'),
    person1LastNameInput: page.locator('#Person1_LastName'),
    person1GenderSelect: page.locator('#Person1_PersonGender'),
    person1JobTitleInput: page.locator('#Person1_PersonJob_Title'),
    person1JobDescriptionInput: page.locator('#Person1_PersonJob_Description'),
    person2: page.locator('#Person2_Person2'),
    person2TitleInput: page.locator('#Person2_Title'),
    person2FirstNameInput: page.locator(
      '[data-testid="Person2_FirstName"] input, [data-testid="Person2_FirstName"], #Person2_FirstName, [name="Person2_FirstName"]'
    ),
    person2MaidenNameInput: page.locator('#Person2_MaidenName'),
    person2LastNameInput: page.locator(
      '[data-testid="Person2_LastName"] input, [data-testid="Person2_LastName"], #Person2_LastName, [name="Person2_LastName"]'
    ),
    person2GenderSelect: page.locator('#Person2_PersonGender'),
    person2JobTitleInput: page.locator('#Person2_PersonJob_Title'),
    person2JobDescriptionInput: page.locator('#Person2_PersonJob_Description'),
    additionalPeople: page.locator('#People'),
    addNewPersonButton: page.locator('#People').locator('button.write-collection-add-item__top'),
    doYouAgreeGroup,
    doYouAgreeYesRadio: doYouAgreeGroup.getByRole('radio', { name: /^Yes$/i }).first(),
    doYouAgreeNoRadio: doYouAgreeGroup.getByRole('radio', { name: /^No$/i }).first(),

    fileUploadInput: page.locator('#DocumentUrl'),
    fileUploadStatusLabel: page.locator('ccd-write-document-field .error-message'),
    textField0Input: page.locator('#TextField0'),
    textField1Input: page.locator('#TextField1'),
    textField2Input: page.locator('#TextField2'),
    textField3Input: page.locator('#TextField3'),
    divorceReasons: page.locator('#DivorceReason .multiple-choice'),
    checkYourAnswers: page.locator('form.check-your-answers'),
    checkYourAnswersHeading: page.locator('.check-your-answers h2'),
    checkYourAnswersTable: page.locator('form.check-your-answers').locator('table'),
    checkYourAnswersSubTable: page.locator('form.check-your-answers').locator('table').locator('table.complex-panel-table table'),
    checkYourAnswersFieldLabels: page.locator('form.check-your-answers').locator('.check-your-answers__field-label'),
    checkYourAnswersChangeLinks: page.locator('form.check-your-answers').getByRole('link', { name: 'Change' }),
    testSubmitButton: page.locator('.check-your-answers [type="submit"]'),

    receiptDayInput: page.locator('#receiptDate-day'),
    receiptMonthInput: page.locator('#receiptDate-month'),
    receiptYearInput: page.locator('#receiptDate-year'),
    tribunalOfficeSelect: page.locator('#managingOffice'),
    claimantIndividualRadio: page.locator('#claimant_TypeOfClaimant-Individual'),
    claimantCompanyRadio: page.locator('#claimant_TypeOfClaimant-Company'),
    claimantOrganisationNameInput: page.locator('#claimant_Company'),
    claimantIndividualFirstNameInput: page.locator('#claimantIndType_claimant_first_names'),
    claimantIndividualLastNameInput: page.locator('#claimantIndType_claimant_last_name'),
    addRespondentButton: page.locator('#respondentCollection button'),
    respondentOneNameInput: page.locator('#respondentCollection_0_respondent_name'),
    respondentOrganisation: page.locator('#respondentCollection_0_respondentType-Organisation'),
    respondentCompanyNameInput: page.locator('#respondentCollection_0_respondentOrganisation'),
    respondentAcasCertifcateSelectYes: page.locator('#respondentCollection_0_respondent_ACAS_question_Yes'),
    respondentAcasCertificateNumberInput: page.locator('#respondentCollection_0_respondent_ACAS'),
    respondentAddressLine1Input: page.locator('#respondentCollection_0_respondent_address__detailAddressLine1'),
    respondentAddressPostcodeInput: page.locator('#respondentCollection_0_respondent_address__detailPostCode'),
    sameAsClaimantWorkAddressYes: page.locator('#claimantWorkAddressQuestion_Yes'),
    claimantRepresentedNo: page.locator('#claimantRepresentedQuestion_No'),
    hearingPreferenceVideo: page.locator('#claimantHearingPreference_hearing_preferences-Video'),

    manualEntryLink: page.locator('.manual-link'),
    claimantAddressLine1Input: page.locator('#claimantType_claimant_addressUK__detailAddressLine1'),
    externalTriageAddressLine1Input: page.locator('#et1ReppedTriageAddress__detailAddressLine1'),
    externalTriagePostTownInput: page.locator('#et1ReppedTriageAddress__detailPostTown'),
    externalTriagePostCodeInput: page.locator('#et1ReppedTriageAddress__detailPostCode'),
    externalTriageAddressSelect: page.locator('#et1ReppedTriageAddress_et1ReppedTriageAddress_addressList'),
    postCodeSearchInput: page.locator('.postcodeLookup input'),
    postCodeSearchButton: page.locator('.postcodeLookup').getByRole('button'),
    addressSelect: page.locator('.postcodeLookup select'),

    refreshModal,
    refreshModalConfirmButton: refreshModal.getByRole('button', { name: 'Ok' }),
    errorMessage: page.locator('.form-group-error .error-message, .govuk-error-message'),
    errorSummary: page.locator('.error-summary, .govuk-error-summary'),
    errorSummaryTitle: page.locator('.error-summary, .govuk-error-summary').locator('h2, h3'),
    errorSummaryItems: page.locator('.error-summary, .govuk-error-summary').locator('.govuk-error-summary__list li, p'),
    eventCreationErrorHeading: page.getByRole('heading', { name: 'The event could not be created' }),
    somethingWentWrongHeading: page.getByRole('heading', { name: /something went wrong/i }),
    validationErrorMessage: page.locator('.validation-error'),
  };
}

export type CreateCaseLocators = ReturnType<typeof buildCreateCaseLocators>;
