export const mockLocations: any[] = [
  {
    'court_venue_id': '10252',
    'epimms_id': '1234',
    'site_name': 'Glasgow Tribunals Centre',
    'region_id': '11',
    'region': 'Scotland',
    'court_type': 'Immigration and Asylum Tribunal',
    'court_type_id': '23',
    'cluster_id': null,
    'cluster_name': null,
    'open_for_public': 'YES',
    'court_address': '20 YORK STREET, GLASGOW',
    'postcode': 'G2  8GT',
    'phone_number': '',
    'closed_date': null,
    'court_location_code': '',
    'dx_address': '',
    'welsh_site_name': '',
    'welsh_court_address': '',
    'court_status': 'Open',
    'court_open_date': null,
    'court_name': 'ATLANTIC QUAY - GLASGOW',
    'venue_name': 'Glasgow',
    'is_case_management_location': 'Y',
    'is_hearing_location': 'Y',
    'welsh_venue_name': '',
    'is_temporary_location': 'N',
    'is_nightingale_court': 'N',
    'location_type': 'COURT',
    'parent_location': '',
    'welsh_court_name': '',
    'uprn': '',
    'venue_ou_code': '',
    'mrd_building_location_id': 'MRD-BLD-011',
    'mrd_venue_id': 'MRD-CRT-0280',
    'service_url': '',
    'fact_url': ''
  },
  {
    'court_venue_id': '10051',
    'epimms_id': '2345',
    'site_name': 'Glasgow New Central Court',
    'region_id': '2',
    'region': 'Midlands',
    'court_type': 'Immigration and Asylum Tribunal',
    'court_type_id': '23',
    'cluster_id': '18',
    'cluster_name': 'West Midlands and Warwickshire',
    'open_for_public': 'YES',
    'court_address': 'PRIORY COURTS, 33 BULL STREET',
    'postcode': 'B4 6DS',
    'phone_number': '',
    'closed_date': null,
    'court_location_code': '',
    'dx_address': '701987 BIRMINGHAM 7',
    'welsh_site_name': '',
    'welsh_court_address': '',
    'court_status': 'Open',
    'court_open_date': null,
    'court_name': 'BIRMINGHAM CIVIL AND FAMILY JUSTICE CENTRE',
    'venue_name': 'Birmingham',
    'is_case_management_location': 'Y',
    'is_hearing_location': 'Y',
    'welsh_venue_name': '',
    'is_temporary_location': 'N',
    'is_nightingale_court': 'N',
    'location_type': 'COURT',
    'parent_location': '',
    'welsh_court_name': '',
    'uprn': '',
    'venue_ou_code': '',
    'mrd_building_location_id': 'MRD-BLD-031',
    'mrd_venue_id': 'MRD-CRT-0079',
    'service_url': '',
    'fact_url': 'https://fact.aat.platform.hmcts.net/courts/birmingham-civil-and-family-justice-centre'
  },
  {
    'court_venue_id': '10052',
    'epimms_id': '2345',
    'site_name': 'Glacier Bay District Court',
    'region_id': '2',
    'region': 'Midlands',
    'court_type': 'Civil',
    'court_type_id': '18',
    'cluster_id': '18',
    'cluster_name': 'West Midlands and Warwickshire',
    'open_for_public': 'YES',
    'court_address': 'PRIORY COURTS, 33 BULL STREET',
    'postcode': 'B4 6DS',
    'phone_number': '',
    'closed_date': null,
    'court_location_code': '',
    'dx_address': '701987 BIRMINGHAM 7',
    'welsh_site_name': '',
    'welsh_court_address': '',
    'court_status': 'Open',
    'court_open_date': null,
    'court_name': 'BIRMINGHAM CIVIL AND FAMILY JUSTICE CENTRE',
    'venue_name': 'Birmingham',
    'is_case_management_location': 'Y',
    'is_hearing_location': 'Y',
    'welsh_venue_name': '',
    'is_temporary_location': 'N',
    'is_nightingale_court': 'N',
    'location_type': 'COURT',
    'parent_location': '',
    'welsh_court_name': '',
    'uprn': '',
    'venue_ou_code': '',
    'mrd_building_location_id': 'MRD-BLD-031',
    'mrd_venue_id': 'MRD-CRT-0079',
    'service_url': '',
    'fact_url': 'https://fact.aat.platform.hmcts.net/courts/birmingham-civil-and-family-justice-centre'
  },
  {
    'court_venue_id': '10054',
    'epimms_id': '3456',
    'site_name': 'Glaswegian Court Society',
    'region_id': '2',
    'region': 'Midlands',
    'court_type': 'Civil',
    'court_type_id': '10',
    'cluster_id': '18',
    'cluster_name': 'West Midlands and Warwickshire',
    'open_for_public': 'YES',
    'court_address': 'PRIORY COURTS, 33 BULL STREET',
    'postcode': 'B4 6DS',
    'phone_number': '',
    'closed_date': null,
    'court_location_code': '',
    'dx_address': '701987 BIRMINGHAM 7',
    'welsh_site_name': '',
    'welsh_court_address': '',
    'court_status': 'Open',
    'court_open_date': null,
    'court_name': 'BIRMINGHAM CIVIL AND FAMILY JUSTICE CENTRE',
    'venue_name': 'Birmingham',
    'is_case_management_location': 'Y',
    'is_hearing_location': 'Y',
    'welsh_venue_name': '',
    'is_temporary_location': 'N',
    'is_nightingale_court': 'N',
    'location_type': 'COURT',
    'parent_location': '',
    'welsh_court_name': '',
    'uprn': '',
    'venue_ou_code': '',
    'mrd_building_location_id': 'MRD-BLD-031',
    'mrd_venue_id': 'MRD-CRT-0079',
    'service_url': '',
    'fact_url': 'https://fact.aat.platform.hmcts.net/courts/birmingham-civil-and-family-justice-centre'
  },
  {
    'court_venue_id': '10053',
    'epimms_id': '4567',
    'site_name': 'Glass Dome Society Family Court',
    'region_id': '2',
    'region': 'Midlands',
    'court_type': 'SSCS',
    'court_type_id': '31',
    'cluster_id': '18',
    'cluster_name': 'West Midlands and Warwickshire',
    'open_for_public': 'YES',
    'court_address': 'PRIORY COURTS, 33 BULL STREET',
    'postcode': 'B4 6DS',
    'phone_number': '',
    'closed_date': null,
    'court_location_code': '',
    'dx_address': '701987 BIRMINGHAM 7',
    'welsh_site_name': '',
    'welsh_court_address': '',
    'court_status': 'Open',
    'court_open_date': null,
    'court_name': 'BIRMINGHAM CIVIL AND FAMILY JUSTICE CENTRE',
    'venue_name': 'Birmingham',
    'is_case_management_location': 'Y',
    'is_hearing_location': 'Y',
    'welsh_venue_name': '',
    'is_temporary_location': 'N',
    'is_nightingale_court': 'N',
    'location_type': 'COURT',
    'parent_location': '',
    'welsh_court_name': '',
    'uprn': '',
    'venue_ou_code': '',
    'mrd_building_location_id': 'MRD-BLD-031',
    'mrd_venue_id': 'MRD-CRT-0079',
    'service_url': '',
    'fact_url': 'https://fact.aat.platform.hmcts.net/courts/birmingham-civil-and-family-justice-centre'
  }
];
