export enum BookingNavigationEvent {
  BACK,
  HOMECONTINUE,
  LOCATIONCONTINUE,
  BOOKINGDATESUBMIT,
  CONFIRMBOOKINGDATESUBMIT,
  CONFIRMBOOKINGSUBMIT,
  CHANGELOCATIONCLICK,
  CHANGEDURATIONCLICK,
  CONFIRM,
  CANCEL
}
