export IDAM_SECRET=***REMOVED*** && export S2S_SECRET=FHYQN3ZQ3BF66XWR && export NODE_CONFIG_DIR=../config && export NODE_CONFIG_ENV=development && export ALLOW_CONFIG_MUTATIONS=1 && export APPINSIGHTS_INSTRUMENTATIONKEY=***REMOVED*** && export LAUNCH_DARKLY_CLIENT_ID=5de6610b23ce5408280f2268 && yarn start:node


# For Demo
# export IDAM_SECRET=***REMOVED*** && export S2S_SECRET=FHYQN3ZQ3BF66XWR && export NODE_CONFIG_DIR=../config && export NODE_CONFIG_ENV=demo && export ALLOW_CONFIG_MUTATIONS=1 && export APPINSIGHTS_INSTRUMENTATIONKEY=***REMOVED*** && export LAUNCH_DARKLY_CLIENT_ID=5de6610b23ce5408280f2268 && yarn start:node