import { ElementRef, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { Moment } from 'moment/moment';
import { NgxMatDateFormats, NgxMatDatetimePicker } from '@angular-material-components/datetime-picker';
import { ThemePalette } from '@angular/material';
import { AbstractFormFieldComponent } from '../base-field/abstract-form-field.component';
import { CaseField } from '../../../domain';
import { FormatTranslatorService } from '../../../services/case-fields/format-translator.service';
export declare class DatetimePickerComponent extends AbstractFormFieldComponent implements OnInit {
    private readonly formatTranslationService;
    private ngxMatDateFormats;
    showSpinners: boolean;
    showSeconds: boolean;
    touchUi: boolean;
    enableMeridian: boolean;
    stepHour: number;
    stepMinute: number;
    stepSecond: number;
    color: ThemePalette;
    disableMinute: boolean;
    hideTime: boolean;
    hideMinutes: boolean;
    startView: string;
    yearSelection: boolean;
    checkTime: boolean;
    stringEdited: boolean;
    private minimumDate;
    private maximumDate;
    minError: boolean;
    maxError: boolean;
    dateControl: FormControl;
    datetimePicker: NgxMatDatetimePicker<any>;
    inputElement: ElementRef<HTMLInputElement>;
    private dateTimeEntryFormat;
    private momentFormat;
    constructor(formatTranslationService: FormatTranslatorService, ngxMatDateFormats: NgxMatDateFormats);
    ngOnInit(): void;
    setDateTimeFormat(): void;
    valueChanged(): void;
    formatValue(): void;
    focusIn(): void;
    toggleClick(): void;
    minDate(caseField: CaseField): Date;
    maxDate(caseField: CaseField): Date;
    configureDatePicker(dateTimePickerFormat: string): void;
    yearSelected(event: Moment): void;
    monthSelected(event: Moment): void;
}
