import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { LocationModel } from '../models/location.model';

@Injectable()
export class LocationService {

  constructor(private readonly http: HttpClient) {}

  public getAllLocations(caseId: string): Observable<LocationModel[]> {
    // const result = this.http.get<LocationModel[]>(`api/locations/getLocations?service=SSCS&locationType=hearing&searchTerm=wal`);
    // return result;
    return of([
      {
        "court_venue_id": "100",
        "epims_id": "219164",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aberdeen Tribunal Hearing Centre",
        "court_name": "ABERDEEN TRIBUNAL HEARING CENTRE",
        "court_status": "Open",
        "region_id": "9",
        "region": "Scotland",
        "court_type_id": "17",
        "court_type": "Employment Tribunal",
        "open_for_public": "Yes",
        "court_address": "AB1, 48 HUNTLY STREET, ABERDEEN",
        "postcode": "AB11 6LT"
      },
      {
        "court_venue_id": "101",
        "epims_id": "219164",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aberdeen Tribunal Hearing Centre",
        "court_name": "ABERDEEN TRIBUNAL HEARING CENTRE",
        "court_status": "Open",
        "region_id": "9",
        "region": "Scotland",
        "court_type_id": "31",
        "court_type": "Social Security and Child Support Tribunal",
        "open_for_public": "Yes",
        "court_address": "AB1, 48 HUNTLY STREET, ABERDEEN",
        "postcode": "AB11 6LT"
      },
      {
        "court_venue_id": "102",
        "epims_id": "827534",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aberystwyth Justice Centre",
        "court_name": "ABERYSTWYTH JUSTICE CENTRE",
        "court_status": "Open",
        "region_id": "8",
        "region": "Wales",
        "court_type_id": "25",
        "court_type": "Magistrates Court",
        "open_for_public": "Yes",
        "court_address": "TREFECHAN",
        "postcode": "SY23 1AS "
      },
      {
        "court_venue_id": "103",
        "epims_id": "827534",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aberystwyth Justice Centre",
        "court_name": "ABERYSTWYTH JUSTICE CENTRE",
        "court_status": "Open",
        "region_id": "8",
        "region": "Wales",
        "court_type_id": "10",
        "court_type": "County Court",
        "open_for_public": "Yes",
        "court_address": "TREFECHAN",
        "postcode": "SY23 1AS "
      },
      {
        "court_venue_id": "104",
        "epims_id": "827534",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aberystwyth Justice Centre",
        "court_name": "ABERYSTWYTH JUSTICE CENTRE",
        "court_status": "Open",
        "region_id": "8",
        "region": "Wales",
        "court_type_id": "18",
        "court_type": "Family Court",
        "open_for_public": "Yes",
        "court_address": "TREFECHAN",
        "postcode": "SY23 1AS "
      },
      {
        "court_venue_id": "105",
        "epims_id": "827534",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aberystwyth Justice Centre",
        "court_name": "ABERYSTWYTH JUSTICE CENTRE",
        "court_status": "Open",
        "region_id": "8",
        "region": "Wales",
        "court_type_id": "31",
        "court_type": "Social Security and Child Support Tribunal",
        "open_for_public": "Yes",
        "court_address": "TREFECHAN",
        "postcode": "SY23 1AS "
      },
      {
        "court_venue_id": "106",
        "epims_id": "450049",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aldershot Justice Centre",
        "court_name": "ALDERSHOT JUSTICE CENTRE",
        "court_status": "Open",
        "region_id": "7",
        "region": "South West",
        "court_type_id": "25",
        "court_type": "Magistrates Court",
        "cluster_id": "9",
        "cluster_name": "Hampshire, Wiltshire, IOW",
        "open_for_public": "Yes",
        "court_address": "THE COURT HOUSE, CIVIC CENTRE, WELLINGTON AVENUE",
        "postcode": "GU11 1NY"
      },
      {
        "court_venue_id": "107",
        "epims_id": "450049",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aldershot Justice Centre",
        "court_name": "ALDERSHOT JUSTICE CENTRE",
        "court_status": "Open",
        "region_id": "7",
        "region": "South West",
        "court_type_id": "10",
        "court_type": "County Court",
        "cluster_id": "9",
        "cluster_name": "Hampshire, Wiltshire, IOW",
        "open_for_public": "Yes",
        "court_address": "THE COURT HOUSE, CIVIC CENTRE, WELLINGTON AVENUE",
        "postcode": "GU11 1NY"
      },
      {
        "court_venue_id": "108",
        "epims_id": "450049",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Aldershot Justice Centre",
        "court_name": "ALDERSHOT JUSTICE CENTRE",
        "court_status": "Open",
        "region_id": "7",
        "region": "South West",
        "court_type_id": "31",
        "court_type": "Social Security and Child Support Tribunal",
        "cluster_id": "9",
        "cluster_name": "Hampshire, Wiltshire, IOW",
        "open_for_public": "Yes",
        "court_address": "THE COURT HOUSE, CIVIC CENTRE, WELLINGTON AVENUE",
        "postcode": "GU11 1NY"
      },
      {
        "court_venue_id": "109",
        "epims_id": "271588",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Amersham Law Courts",
        "court_name": "AMERSHAM LAW COURTS",
        "court_status": "Open",
        "region_id": "6",
        "region": "South East",
        "court_type_id": "15",
        "court_type": "Crown Court",
        "cluster_id": "17",
        "cluster_name": "Thames Valley",
        "open_for_public": "Yes",
        "court_address": "KING GEORGE V ROAD AMERSHAM BUCKINGHAMSHIRE",
        "postcode": "HP6 5AJ"
      },
      {
        "court_venue_id": "110",
        "epims_id": "239985",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Ashford Tribunal Hearing Centre",
        "court_name": "ASHFORD TRIBUNAL HEARING CENTRE",
        "court_status": "Open",
        "region_id": "6",
        "region": "South East",
        "court_type_id": "17",
        "court_type": "Employment Tribunal",
        "cluster_id": "11",
        "cluster_name": "Kent",
        "open_for_public": "Yes",
        "court_address": "COUNTY SQUARE",
        "postcode": "TN23 1YB"
      },
      {
        "court_venue_id": "111",
        "epims_id": "239985",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Ashford Tribunal Hearing Centre",
        "court_name": "ASHFORD TRIBUNAL HEARING CENTRE",
        "court_status": "Open",
        "region_id": "6",
        "region": "South East",
        "court_type_id": "31",
        "court_type": "Social Security and Child Support Tribunal",
        "cluster_id": "11",
        "cluster_name": "Kent",
        "open_for_public": "Yes",
        "court_address": "COUNTY SQUARE",
        "postcode": "TN23 1YB"
      },
      {
        "court_venue_id": "112",
        "epims_id": "817181",
        "is_hearing_location": "N",
        "is_case_management_location": "Y",
        "site_name": "Aylesbury Crown Court",
        "court_name": "AYLESBURY CROWN COURT",
        "court_status": "Open",
        "region_id": "6",
        "region": "South East",
        "court_type_id": "15",
        "court_type": "Crown Court",
        "cluster_id": "17",
        "cluster_name": "Thames Valley",
        "open_for_public": "Yes",
        "court_address": "WALTON STREET, AYLESBURY",
        "postcode": "HP21 7FT"
      },
      {
        "court_venue_id": "113",
        "epims_id": "206150",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Ayr Social Security and Child Support Tribunal",
        "court_name": "AYR SOCIAL SECURITY AND CHILD SUPPORT TRIBUNAL",
        "court_status": "Closed",
        "region_id": "9",
        "region": "Scotland",
        "court_type_id": "31",
        "court_type": "Social Security and Child Support Tribunal",
        "open_for_public": "No",
        "court_address": "RUSSELL HOUSE, KINGSTREET, STRATHCLYDE, ARYSHIRE",
        "postcode": "KA8 0BD",
        "phone_number": "0300 790 6234"
      },
      {
        "court_venue_id": "114",
        "epims_id": "218723",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Barkingside Magistrates\' Court",
        "court_name": "BARKINGSIDE MAGISTRATES COURT",
        "court_status": "Open",
        "region_id": "2",
        "region": "London",
        "court_type_id": "25",
        "court_type": "Magistrates Court",
        "cluster_name": "Magistrates",
        "open_for_public": "Yes",
        "court_address": "CRANBROOK ROAD, IIFORD",
        "postcode": "IG6 1HW"
      },
      {
        "court_venue_id": "115",
        "epims_id": "229786",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Barnet Civil and Family Centre",
        "court_name": "BARNET CIVIL AND FAMILY COURTS CENTRE",
        "court_status": "Open",
        "region_id": "2",
        "region": "London",
        "court_type_id": "10",
        "court_type": "County Court",
        "cluster_name": "Civil and Family",
        "open_for_public": "Yes",
        "court_address": "ST MARY\'S COURT, REGENTS PARK ROAD",
        "postcode": "N3 1BQ",
        "dx_address": "122570 FINCHLEY CHURCH END"
      },
      {
        "court_venue_id": "116",
        "epims_id": "229786",
        "is_hearing_location": "Y",
        "is_case_management_location": "Y",
        "site_name": "Barnet Civil and Family Centre",
        "court_name": "BARNET CIVIL AND FAMILY COURTS CENTRE",
        "court_status": "Open",
        "region_id": "2",
        "region": "London",
        "court_type_id": "18",
        "court_type": "Family Court",
        "cluster_name": "Civil and Family",
        "open_for_public": "Yes",
        "court_address": "ST MARY\'S COURT, REGENTS PARK ROAD",
        "postcode": "N3 1BQ",
        "dx_address": "122570 FINCHLEY CHURCH END"
      }]);
  }
}