export enum SpecificAccessState {
  SPECIFIC_ACCESS_REVIEW,
  SPECIFIC_ACCESS_DURATION,
  SPECIFIC_ACCESS_APPROVED,
  SPECIFIC_ACCESS_INFORMATION,
  SPECIFIC_ACCESS_DENIED,
  SPECIFIC_ACCESS_DUPLICATE_RECORD
}
