import { OnInit } from '@angular/core';
import { AbstractFieldWriteComponent } from '../base-field/abstract-field-write.component';
import { FormControl, FormGroup } from '@angular/forms';
import { OrganisationConverter, SimpleOrganisationModel } from '../../../domain/organisation';
import { Observable } from 'rxjs';
import { OrganisationService, OrganisationVm } from '../../../services/organisation';
import { WindowService } from '../../../services';
export declare class WriteOrganisationFieldComponent extends AbstractFieldWriteComponent implements OnInit {
    private readonly organisationService;
    private readonly organisationConverter;
    private readonly windowService;
    private static readonly EMPTY_SIMPLE_ORG;
    private static readonly MAX_RESULT_COUNT;
    private static readonly ORGANISATION_ID;
    private static readonly ORGANISATION_NAME;
    private static readonly PRE_POPULATE_TO_USERS_ORGANISATION;
    private static readonly ORGANISATION_DETAILS;
    private static readonly YES;
    private static readonly MANDATORY;
    defaultOrg: any;
    organisationFormGroup: FormGroup;
    searchOrgTextFormControl: FormControl;
    organisationIDFormControl: FormControl;
    organisationNameFormControl: FormControl;
    organisations$: Observable<OrganisationVm[]>;
    searchOrgValue$: Observable<string>;
    simpleOrganisations$: Observable<SimpleOrganisationModel[]>;
    selectedOrg$: Observable<SimpleOrganisationModel>;
    constructor(organisationService: OrganisationService, organisationConverter: OrganisationConverter, windowService: WindowService);
    ngOnInit(): void;
    private preSelectDefaultOrg;
    private preSelectEmptyOrg;
    private instantiateOrganisationFormGroup;
    private addOrganisationValidators;
    onSearchOrg(orgSearchText: string): void;
    searchOrg(organisations: OrganisationVm[], lowerOrgSearchText: string): SimpleOrganisationModel[];
    private searchCriteria;
    private searchWithSpace;
    trimAll(oldText: string): string;
    selectOrg(selectedOrg: SimpleOrganisationModel): void;
    deSelectOrg(): void;
}
