import { NgxMatDateFormats, NgxMatDatetimepicker } from '@angular-material-components/datetime-picker';
import { ElementRef, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { ThemePalette } from '@angular/material/core';
import { Moment } from 'moment/moment';
import { CaseField } from '../../../domain/definition/case-field.model';
import { FormatTranslatorService } from '../../../services/case-fields/format-translator.service';
import { AbstractFormFieldComponent } from '../base-field/abstract-form-field.component';
import * as i0 from "@angular/core";
export declare class DatetimePickerComponent extends AbstractFormFieldComponent implements OnInit {
    private readonly formatTranslationService;
    private readonly ngxMatDateFormats;
    showSpinners: boolean;
    showSeconds: boolean;
    touchUi: boolean;
    enableMeridian: boolean;
    stepHour: number;
    stepMinute: number;
    stepSecond: number;
    color: ThemePalette;
    disableMinute: boolean;
    hideTime: boolean;
    hideMinutes: boolean;
    startView: string;
    yearSelection: boolean;
    checkTime: boolean;
    stringEdited: boolean;
    minError: boolean;
    maxError: boolean;
    dateTimeEntryFormat: string;
    datetimePicker: NgxMatDatetimepicker<any>;
    inputElement: ElementRef<HTMLInputElement>;
    dateControl: FormControl;
    private minimumDate;
    private maximumDate;
    private momentFormat;
    constructor(formatTranslationService: FormatTranslatorService, ngxMatDateFormats: NgxMatDateFormats);
    ngOnInit(): void;
    setDateTimeFormat(): void;
    valueChanged(): void;
    focusIn(): void;
    focusOut(): void;
    toggleClick(): void;
    minDate(caseField: CaseField): Date;
    maxDate(caseField: CaseField): Date;
    configureDatePicker(dateTimePickerFormat: string): void;
    yearSelected(event: Moment): void;
    monthSelected(event: Moment): void;
    private formatValueAndSetErrors;
    static ɵfac: i0.ɵɵFactoryDeclaration<DatetimePickerComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DatetimePickerComponent, "ccd-datetime-picker", never, { "dateControl": "dateControl"; }, {}, never, never, false, never>;
}
//# sourceMappingURL=datetime-picker.component.d.ts.map