
nodejs:
  applicationPort: 3000
  memoryLimits: 1024Mi
  cpuLimits: 1000m
  environment:
    REFORM_TEAM: rpx
    REFORM_SERVICE_NAME: xui-webapp
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    XUI_ENV: preview
    S2S_SECRET: ${S2S_SECRET}
    IDAM_SECRET: ${IDAM_SECRET}
  keyVaults:
    rpa:
      resourceGroup: rpa
      secrets:
        - test-email
        - jui-s2s-token
        - decrypt-key
        - jui-oauth2-token
        - fr-email
        - fr-password
        - sscs-email
        - sscs-password
        - AppInsightsInstrumentationKey
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
