import { WizardPageField } from '../../components/case-editor/domain/wizard-page-field.model';
import { Orderable } from '../order';
import { AccessControlList } from './access-control-list.model';
import { FieldType } from './field-type.model';
export declare class CaseField implements Orderable {
    id: string;
    hidden: boolean;
    hiddenCannotChange: boolean;
    label: string;
    order?: number;
    field_type: FieldType;
    hint_text?: string;
    security_label?: string;
    display_context: string;
    display_context_parameter?: string;
    month_format?: string;
    show_condition?: string;
    show_summary_change_option?: boolean;
    show_summary_content_option?: number;
    acls?: AccessControlList[];
    metadata?: boolean;
    formatted_value?: any;
    retain_hidden_value: boolean;
    wizardProps?: WizardPageField;
    _value: any;
    _list_items: any;
    get value(): any;
    set value(value: any);
    get list_items(): any;
    set list_items(items: any);
    get dateTimeEntryFormat(): string;
    get dateTimeDisplayFormat(): string;
    isComplexDisplay(): boolean;
    isComplexEntry(): boolean;
    isReadonly(): boolean;
    isOptional(): boolean;
    isMandatory(): boolean;
    isCollection(): boolean;
    isComplex(): boolean;
    isDynamic(): boolean;
    isCaseLink(): boolean;
    extractBracketValue(fmt: string, paramName: string, leftBracket?: string, rightBracket?: string): string;
}
//# sourceMappingURL=case-field.model.d.ts.map