name: Populate Preview Deployment ID

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_EXUI_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_EXUI_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
      - name: Populate preview deployment ID
        run: |
          cd charts/xui-webapp
          sed -i 's/PREVIEW_DEPLOYMENT_ID:.*/PREVIEW_DEPLOYMENT_ID: exui-preview-deployment-${{ github.event.number }}/' values.preview.template.yaml
          cd ../..
          git status
          git diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Setting Preview Deployment ID"
          git push
        shell: bash
