name: Populate Preview Deployment ID

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_EXUI_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_EXUI_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
      - name: Running script to populate preview deployment ID
        run: ./populatepreviewdeploymentid.sh ${{ github.workspace }} ${{ github.ref }} ${{ github.event.number }}
        working-directory: ./
        shell: bash
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: false
          commit_message: "Setting Preview Deployment ID"
          branch: master
